//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by RESOURCE.RC
//
#define IDOK2                           2
#define IDOK3                           3
#define MAIN                            101
#define IDR_MENU1                       102
#define IDD_DIALOG1                     103
#define IDI_ICON1                       110
#define IDC_BUTTON1                     1000
#define IDC_CHECK1                      1001
#define IDC_BUTTON8                     1001
#define IDC_BUTTON2                     1002
#define IDC_BUTTON9                     1002
#define IDC_BUTTON3                     1003
#define IDC_BUTTON4                     1004
#define IDC_BUTTON5                     1005
#define IDC_BUTTON6                     1006
#define IDC_BUTTON7                     1007
#define IDC_COMBO1                      1015
#define IDC_LIST1                       1016
#define IDC_COMBO2                      1017
#define IDC_RADIO1                      1018
#define IDC_STATIC2                     1019
#define IDC_EDIT1                       1021
#define IDC_CHECK2                      1023
#define IDC_USER1                       1024
#define IDC_HORZ                        1026
#define IDC_VERT                        1027
#define IDC_CLOSEDLG                    1028
#define ID_FILE_TEST1                   40003
#define ID_FILE_TEST2                   40004
#define ID_FILE_TEST3                   40005
#define ID_FILE_TEST4                   40006
#define ID_RUN_TEST                     40007
#define ID_NOPOP_TEST                   40008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        111
#define _APS_NEXT_COMMAND_VALUE         40009
#define _APS_NEXT_CONTROL_VALUE         1029
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
