import javax.swing.*;  
import java.awt.event.*;  
import java.awt.*;  
 //  AUTO ...
public class OneButton_Applet extends JApplet  
{  
public void init()  
  {  
  JButton button1 = new JButton( "Push Me");
  setBackground(Color.lightGray);  
  getContentPane().add(button1,"Center");
}   // //init()...
}   // //OneButton_Applet...

//  FlowCode File: OneButton_Applet.ins...
//  Export  File: OneButton_Applet.java...
//  Export  Date: 02:06:20 PM - 27:Aug:1999...

