/**  C:\WINDOWS\Profiles\luis\Desktop\TreeTool\ItemAction.java  **/   //   FILE:C:\WINDOWS\Profiles\luis\Desktop\TreeTool\ItemAction.java...
   //  // // Author: C Dare-Edwards......
   //  // // ......
   //  // // cdare-edwards@mcsoftware.com.au......
   //  // // ......
   //  // //  Copyright Conrad Dare-Edwards......
   //  // //......
   //  // //  The copyright to the computer program (s) herein......
   //  // //  is the property of Conrad Dare-Edwards. The program (s)......
   //  // //  may be used and/or copied only with the written......
   //  // //  permission of Conrad Dare-Edwards or in accordance......
   //  // //  with the terms and conditions stipulated in the......
   //  // //  agreement/contract under which the program (s) have......
   //  // //  been supplied.......
  import java.applet.*;  
  import java.net.*;  
  import java.awt.Event; 
   //  //  AUTO ......
public class ItemAction extends java.lang.Object {  
  String m_status;  
  URL m_doc;  
  String m_docTarget;  
  Applet m_applet;  
  public static boolean m_showURL =true;  
   //  // ///////////////////////////////////////////////////////////////......
   //  // // initalisation......
public ItemAction(Applet applet )  
  {  
  m_applet =applet;  
}  
 //  // // set status string and add URL link to the end if present......
public void setStatus( String status )  
   //  // // copy status sting......
  {  
  if( status != null )  
  
     //  // /auto path//......
    m_status =new String( status );  
     //  // // and add url if present......
   
  if( m_doc != null && m_showURL )  
  
     //  // /auto path//......
    {  
    if( m_status == null )  
    
      m_status =new String();  
    else  
      m_status =m_status.concat(" - ");  
     
    m_status =m_status.concat( m_doc.toString() );  
   
} }  
public void setDocument( URL doc, String target )  
  {  
  m_doc =doc;  
  m_docTarget =target;  
  setStatus( m_status );  
}  
 //  // ////////////////////////////////////////////////////////////////////......
 //  // // actavtion actions......
public void showStatus( )  
  {  
  if( m_status != null )  
  
     //  // /auto path//......
    m_applet.showStatus( m_status );  
   
}  
Event e = new Event( m_applet , TreeTool.TREETOOL_MOUSESELCTION   , new String("test") ); // Event e = new Event( m_applet , Event.MOUSE_DOWN , new String("test") );...
public void actionMouseSelection( )  //Sends a MOUSE_DOWN to the applet //  public void showDocument( ) ...
  {  
  e.arg = m_doc;
  m_applet.handleEvent( e );
   //    System.out.println( m_docTarget + "   :  " + m_doc + "  <<showDocument action from ItemAction \n");...
  if( m_doc != null )  
  
     //  // /auto path//......
    {  
    AppletContext ac =m_applet.getAppletContext();  
    //  ac.showDocument( m_doc, m_docTarget ); 
   
} }  
 //  //  FlowCode File: ItemAction.java.ins......
 //  //  Export  File: ItemAction.java......
 //  //  Export  Date: 02:51:25 AM - 30:Aug:1999......
}  

//  FlowCode File: ItemAction.java.ins...
//  Export  File: ItemAction.java...
//  Export  Date: 12:30:52 PM - 01:Sep:1999...

